name: Go CI

on:
  push:
    branches:
      - main
      - master
      - dev
      - develop
  pull_request:

permissions:
  contents: read

jobs:
  lint:
    name: Lint Code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: stable
      - name: Install Dependencies
        run: go mod tidy

      - name: Install golangci-lint
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $HOME/go/bin latest
          echo "$HOME/go/bin" >> $GITHUB_PATH

      - name: Run golangci-lint in all go.mod folders
        run: |
          find . -name 'go.mod' -execdir golangci-lint run ./... --timeout=5m \;

      - name: Run Tests 
        run: go test ./... -v
